export const ORDER_ASYNC_START = 'ORDER_ASYNC_START';
export const ORDER_ASYNC_SUCCESS = 'ORDER_ASYNC_SUCCESS';
export const ORDER_ASYNC_FAILURE = 'ORDER_ASYNC_FAILURE';
export const CHANGE_TAB = 'CHANGE_TAB';
export const GET_SUB_DATA = 'GET_SUB_DATA';
export const SET_SUB_DATA_KEY = 'SET_SUB_DATA_KEY';