
export const LOADING_USER_SUMMARY = 'LOADING_USER_SUMMARY';

export const LOADING_USER_SUMMARY_SUCCESS = 'LOADING_USER_SUMMARY_SUCCESS';

export const LOADING_USER_SUMMARY_FAILURE = 'LOADING_USER_SUMMARY_FAILURE';